name: check label of PR to main

on:
  pull_request:
    branches:
      - main
    types:
      - synchronize
      - labeled
      - unlabeled
      - opened
      - reopened

jobs:
  check_label:
    if: github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    permissions:
      contents: read

    timeout-minutes: 10
    env:
      MASTER_BRANCH: main
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Ensure authentication
        run: gh auth status

      - name: check label of PR to main
        continue-on-error: false
        run: |
          i=0
          
          # PRのラベル情報を取得
          items=$(GH_TOKEN=${{ secrets.GITHUB_TOKEN }} gh pr view ${{ github.event.number }} --repo "${{ github.repository }}" --json labels -q '.labels')

          # ラベルが付いていない場合のチェック
          if [ -z "$items" ] || [ "$items" = "[]" ]; then
              echo "エラー: PR にラベルが付いていません"
              exit 1
          fi

          IFS=$'\n'
          for item in $(echo "$items" | jq -r 'map(.name) | .[]'); do
              case "${item}" in
                  "major"|"minor"|"patch")
                      (( ++i ))
                      ;;
              esac
          done

          # ラベルの数をチェック
          if [ $i -eq 0 ]; then
              echo "エラー: 更新するリリースバージョンのラベルを付けてください (major, minor, patch のいずれか)"
              exit 1
          fi
          if [ $i -gt 1 ]; then
              echo "エラー: リリースバージョンのラベルを2つ以上つけないでください"
              exit 1
          fi

          echo "✅ チェック完了: 適切なラベルが1つ設定されています。"